name:                LatteCompiler
version:             0.1.0.0
github:              "mizworski/LatteCompiler"
license:             BSD3
author:              "Michal Izworski"
maintainer:          "m.izworski7@gmail.com"
copyright:           "2018 Michal Izworski"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mizworski/LatteCompiler#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- array
- mtl

library:
  source-dirs: src

executables:
  LatteCompiler-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - LatteCompiler

tests:
  LatteCompiler-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - LatteCompiler
